# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.4

# Default target executed when no arguments are given to make.
default_target: all

.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:


#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:


# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list


# Suppress display of executed commands.
$(VERBOSE).SILENT:


# A target that is always out of date.
cmake_force:

.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/local/Cellar/cmake/3.4.3/bin/cmake

# The command to remove a file.
RM = /usr/local/Cellar/cmake/3.4.3/bin/cmake -E remove -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /Users/bandi/desktop/chess-engine

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /Users/bandi/desktop/chess-engine

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake cache editor..."
	/usr/local/Cellar/cmake/3.4.3/bin/ccmake -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache

.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/local/Cellar/cmake/3.4.3/bin/cmake -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache

.PHONY : rebuild_cache/fast

# Special rule for the target test
test:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running tests..."
	/usr/local/Cellar/cmake/3.4.3/bin/ctest --force-new-ctest-process $(ARGS)
.PHONY : test

# Special rule for the target test
test/fast: test

.PHONY : test/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /Users/bandi/desktop/chess-engine/CMakeFiles /Users/bandi/desktop/chess-engine/CMakeFiles/progress.marks
	$(MAKE) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /Users/bandi/desktop/chess-engine/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean

.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named ChessTest

# Build rule for target.
ChessTest: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 ChessTest
.PHONY : ChessTest

# fast build rule for target.
ChessTest/fast:
	$(MAKE) -f CMakeFiles/ChessTest.dir/build.make CMakeFiles/ChessTest.dir/build
.PHONY : ChessTest/fast

test/TestBoard.o: test/TestBoard.cpp.o

.PHONY : test/TestBoard.o

# target to build an object file
test/TestBoard.cpp.o:
	$(MAKE) -f CMakeFiles/ChessTest.dir/build.make CMakeFiles/ChessTest.dir/test/TestBoard.cpp.o
.PHONY : test/TestBoard.cpp.o

test/TestBoard.i: test/TestBoard.cpp.i

.PHONY : test/TestBoard.i

# target to preprocess a source file
test/TestBoard.cpp.i:
	$(MAKE) -f CMakeFiles/ChessTest.dir/build.make CMakeFiles/ChessTest.dir/test/TestBoard.cpp.i
.PHONY : test/TestBoard.cpp.i

test/TestBoard.s: test/TestBoard.cpp.s

.PHONY : test/TestBoard.s

# target to generate assembly for a file
test/TestBoard.cpp.s:
	$(MAKE) -f CMakeFiles/ChessTest.dir/build.make CMakeFiles/ChessTest.dir/test/TestBoard.cpp.s
.PHONY : test/TestBoard.cpp.s

test/TestFENParser.o: test/TestFENParser.cpp.o

.PHONY : test/TestFENParser.o

# target to build an object file
test/TestFENParser.cpp.o:
	$(MAKE) -f CMakeFiles/ChessTest.dir/build.make CMakeFiles/ChessTest.dir/test/TestFENParser.cpp.o
.PHONY : test/TestFENParser.cpp.o

test/TestFENParser.i: test/TestFENParser.cpp.i

.PHONY : test/TestFENParser.i

# target to preprocess a source file
test/TestFENParser.cpp.i:
	$(MAKE) -f CMakeFiles/ChessTest.dir/build.make CMakeFiles/ChessTest.dir/test/TestFENParser.cpp.i
.PHONY : test/TestFENParser.cpp.i

test/TestFENParser.s: test/TestFENParser.cpp.s

.PHONY : test/TestFENParser.s

# target to generate assembly for a file
test/TestFENParser.cpp.s:
	$(MAKE) -f CMakeFiles/ChessTest.dir/build.make CMakeFiles/ChessTest.dir/test/TestFENParser.cpp.s
.PHONY : test/TestFENParser.cpp.s

test/TestGame.o: test/TestGame.cpp.o

.PHONY : test/TestGame.o

# target to build an object file
test/TestGame.cpp.o:
	$(MAKE) -f CMakeFiles/ChessTest.dir/build.make CMakeFiles/ChessTest.dir/test/TestGame.cpp.o
.PHONY : test/TestGame.cpp.o

test/TestGame.i: test/TestGame.cpp.i

.PHONY : test/TestGame.i

# target to preprocess a source file
test/TestGame.cpp.i:
	$(MAKE) -f CMakeFiles/ChessTest.dir/build.make CMakeFiles/ChessTest.dir/test/TestGame.cpp.i
.PHONY : test/TestGame.cpp.i

test/TestGame.s: test/TestGame.cpp.s

.PHONY : test/TestGame.s

# target to generate assembly for a file
test/TestGame.cpp.s:
	$(MAKE) -f CMakeFiles/ChessTest.dir/build.make CMakeFiles/ChessTest.dir/test/TestGame.cpp.s
.PHONY : test/TestGame.cpp.s

test/TestHelpers.o: test/TestHelpers.cpp.o

.PHONY : test/TestHelpers.o

# target to build an object file
test/TestHelpers.cpp.o:
	$(MAKE) -f CMakeFiles/ChessTest.dir/build.make CMakeFiles/ChessTest.dir/test/TestHelpers.cpp.o
.PHONY : test/TestHelpers.cpp.o

test/TestHelpers.i: test/TestHelpers.cpp.i

.PHONY : test/TestHelpers.i

# target to preprocess a source file
test/TestHelpers.cpp.i:
	$(MAKE) -f CMakeFiles/ChessTest.dir/build.make CMakeFiles/ChessTest.dir/test/TestHelpers.cpp.i
.PHONY : test/TestHelpers.cpp.i

test/TestHelpers.s: test/TestHelpers.cpp.s

.PHONY : test/TestHelpers.s

# target to generate assembly for a file
test/TestHelpers.cpp.s:
	$(MAKE) -f CMakeFiles/ChessTest.dir/build.make CMakeFiles/ChessTest.dir/test/TestHelpers.cpp.s
.PHONY : test/TestHelpers.cpp.s

test/TestLocation.o: test/TestLocation.cpp.o

.PHONY : test/TestLocation.o

# target to build an object file
test/TestLocation.cpp.o:
	$(MAKE) -f CMakeFiles/ChessTest.dir/build.make CMakeFiles/ChessTest.dir/test/TestLocation.cpp.o
.PHONY : test/TestLocation.cpp.o

test/TestLocation.i: test/TestLocation.cpp.i

.PHONY : test/TestLocation.i

# target to preprocess a source file
test/TestLocation.cpp.i:
	$(MAKE) -f CMakeFiles/ChessTest.dir/build.make CMakeFiles/ChessTest.dir/test/TestLocation.cpp.i
.PHONY : test/TestLocation.cpp.i

test/TestLocation.s: test/TestLocation.cpp.s

.PHONY : test/TestLocation.s

# target to generate assembly for a file
test/TestLocation.cpp.s:
	$(MAKE) -f CMakeFiles/ChessTest.dir/build.make CMakeFiles/ChessTest.dir/test/TestLocation.cpp.s
.PHONY : test/TestLocation.cpp.s

test/TestMain.o: test/TestMain.cpp.o

.PHONY : test/TestMain.o

# target to build an object file
test/TestMain.cpp.o:
	$(MAKE) -f CMakeFiles/ChessTest.dir/build.make CMakeFiles/ChessTest.dir/test/TestMain.cpp.o
.PHONY : test/TestMain.cpp.o

test/TestMain.i: test/TestMain.cpp.i

.PHONY : test/TestMain.i

# target to preprocess a source file
test/TestMain.cpp.i:
	$(MAKE) -f CMakeFiles/ChessTest.dir/build.make CMakeFiles/ChessTest.dir/test/TestMain.cpp.i
.PHONY : test/TestMain.cpp.i

test/TestMain.s: test/TestMain.cpp.s

.PHONY : test/TestMain.s

# target to generate assembly for a file
test/TestMain.cpp.s:
	$(MAKE) -f CMakeFiles/ChessTest.dir/build.make CMakeFiles/ChessTest.dir/test/TestMain.cpp.s
.PHONY : test/TestMain.cpp.s

test/TestPiece.o: test/TestPiece.cpp.o

.PHONY : test/TestPiece.o

# target to build an object file
test/TestPiece.cpp.o:
	$(MAKE) -f CMakeFiles/ChessTest.dir/build.make CMakeFiles/ChessTest.dir/test/TestPiece.cpp.o
.PHONY : test/TestPiece.cpp.o

test/TestPiece.i: test/TestPiece.cpp.i

.PHONY : test/TestPiece.i

# target to preprocess a source file
test/TestPiece.cpp.i:
	$(MAKE) -f CMakeFiles/ChessTest.dir/build.make CMakeFiles/ChessTest.dir/test/TestPiece.cpp.i
.PHONY : test/TestPiece.cpp.i

test/TestPiece.s: test/TestPiece.cpp.s

.PHONY : test/TestPiece.s

# target to generate assembly for a file
test/TestPiece.cpp.s:
	$(MAKE) -f CMakeFiles/ChessTest.dir/build.make CMakeFiles/ChessTest.dir/test/TestPiece.cpp.s
.PHONY : test/TestPiece.cpp.s

test/TestPlayer.o: test/TestPlayer.cpp.o

.PHONY : test/TestPlayer.o

# target to build an object file
test/TestPlayer.cpp.o:
	$(MAKE) -f CMakeFiles/ChessTest.dir/build.make CMakeFiles/ChessTest.dir/test/TestPlayer.cpp.o
.PHONY : test/TestPlayer.cpp.o

test/TestPlayer.i: test/TestPlayer.cpp.i

.PHONY : test/TestPlayer.i

# target to preprocess a source file
test/TestPlayer.cpp.i:
	$(MAKE) -f CMakeFiles/ChessTest.dir/build.make CMakeFiles/ChessTest.dir/test/TestPlayer.cpp.i
.PHONY : test/TestPlayer.cpp.i

test/TestPlayer.s: test/TestPlayer.cpp.s

.PHONY : test/TestPlayer.s

# target to generate assembly for a file
test/TestPlayer.cpp.s:
	$(MAKE) -f CMakeFiles/ChessTest.dir/build.make CMakeFiles/ChessTest.dir/test/TestPlayer.cpp.s
.PHONY : test/TestPlayer.cpp.s

test/TestSimpleSquare.o: test/TestSimpleSquare.cpp.o

.PHONY : test/TestSimpleSquare.o

# target to build an object file
test/TestSimpleSquare.cpp.o:
	$(MAKE) -f CMakeFiles/ChessTest.dir/build.make CMakeFiles/ChessTest.dir/test/TestSimpleSquare.cpp.o
.PHONY : test/TestSimpleSquare.cpp.o

test/TestSimpleSquare.i: test/TestSimpleSquare.cpp.i

.PHONY : test/TestSimpleSquare.i

# target to preprocess a source file
test/TestSimpleSquare.cpp.i:
	$(MAKE) -f CMakeFiles/ChessTest.dir/build.make CMakeFiles/ChessTest.dir/test/TestSimpleSquare.cpp.i
.PHONY : test/TestSimpleSquare.cpp.i

test/TestSimpleSquare.s: test/TestSimpleSquare.cpp.s

.PHONY : test/TestSimpleSquare.s

# target to generate assembly for a file
test/TestSimpleSquare.cpp.s:
	$(MAKE) -f CMakeFiles/ChessTest.dir/build.make CMakeFiles/ChessTest.dir/test/TestSimpleSquare.cpp.s
.PHONY : test/TestSimpleSquare.cpp.s

test/TestSimpleSquareFactory.o: test/TestSimpleSquareFactory.cpp.o

.PHONY : test/TestSimpleSquareFactory.o

# target to build an object file
test/TestSimpleSquareFactory.cpp.o:
	$(MAKE) -f CMakeFiles/ChessTest.dir/build.make CMakeFiles/ChessTest.dir/test/TestSimpleSquareFactory.cpp.o
.PHONY : test/TestSimpleSquareFactory.cpp.o

test/TestSimpleSquareFactory.i: test/TestSimpleSquareFactory.cpp.i

.PHONY : test/TestSimpleSquareFactory.i

# target to preprocess a source file
test/TestSimpleSquareFactory.cpp.i:
	$(MAKE) -f CMakeFiles/ChessTest.dir/build.make CMakeFiles/ChessTest.dir/test/TestSimpleSquareFactory.cpp.i
.PHONY : test/TestSimpleSquareFactory.cpp.i

test/TestSimpleSquareFactory.s: test/TestSimpleSquareFactory.cpp.s

.PHONY : test/TestSimpleSquareFactory.s

# target to generate assembly for a file
test/TestSimpleSquareFactory.cpp.s:
	$(MAKE) -f CMakeFiles/ChessTest.dir/build.make CMakeFiles/ChessTest.dir/test/TestSimpleSquareFactory.cpp.s
.PHONY : test/TestSimpleSquareFactory.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... rebuild_cache"
	@echo "... test"
	@echo "... ChessTest"
	@echo "... test/TestBoard.o"
	@echo "... test/TestBoard.i"
	@echo "... test/TestBoard.s"
	@echo "... test/TestFENParser.o"
	@echo "... test/TestFENParser.i"
	@echo "... test/TestFENParser.s"
	@echo "... test/TestGame.o"
	@echo "... test/TestGame.i"
	@echo "... test/TestGame.s"
	@echo "... test/TestHelpers.o"
	@echo "... test/TestHelpers.i"
	@echo "... test/TestHelpers.s"
	@echo "... test/TestLocation.o"
	@echo "... test/TestLocation.i"
	@echo "... test/TestLocation.s"
	@echo "... test/TestMain.o"
	@echo "... test/TestMain.i"
	@echo "... test/TestMain.s"
	@echo "... test/TestPiece.o"
	@echo "... test/TestPiece.i"
	@echo "... test/TestPiece.s"
	@echo "... test/TestPlayer.o"
	@echo "... test/TestPlayer.i"
	@echo "... test/TestPlayer.s"
	@echo "... test/TestSimpleSquare.o"
	@echo "... test/TestSimpleSquare.i"
	@echo "... test/TestSimpleSquare.s"
	@echo "... test/TestSimpleSquareFactory.o"
	@echo "... test/TestSimpleSquareFactory.i"
	@echo "... test/TestSimpleSquareFactory.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

